apiVersion: v1
kind: ServiceAccount
metadata:
  name: jhipster-prometheus-sa
  namespace: sabino-labs
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-role
  namespace: sabino-labs
rules:
  - apiGroups: ['']
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources:
      - configmaps
    verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
# limit to the namespace
kind: RoleBinding
metadata:
  name: prometheus-rb
  namespace: sabino-labs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-role
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: sabino-labs
spec:
  replicas: 1
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchLabels:
      team: sabino-labs
  resources:
    requests:
      memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: sabino-labs
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: prometheus
