jobs:
  - job: Test
    pool:
      vmImage: 'Ubuntu 16.04'
    variables:
      NODE_VERSION: 12.16.1
      SPRING_OUTPUT_ANSI_ENABLED: NEVER
      SPRING_JPA_SHOW_SQL: false
      NG_CLI_ANALYTICS: 'false'
    steps:
      #----------------------------------------------------------------------
      # Tests
      #----------------------------------------------------------------------
      - script: |
          chmod +x gradlew
          ./gradlew checkstyleNohttp
          ./gradlew clean test integrationTest
        displayName: 'TESTS: backend'
      - script: ./gradlew bootJar -Pprod -x test
        displayName: 'TESTS: packaging'
