apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: sabinoLabsRepo/sabinolabs
      context: ../spring-boot-microservice
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
