version: '3.8'
services:
  sabinolabs-app:
    image: sabinolabs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://sabinolabs-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=SabinoLabs
      - JHIPSTER_CACHE_REDIS_SERVER=redis://sabinolabs-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - JHIPSTER_SLEEP=30
  sabinolabs-mongodb:
    image: mongo:4.4.6
    ports:
      - 127.0.0.1:27017:27017
     volumes:
       - ~/volumes/SabinoLabs/mongodb/:/data/db/
  sabinolabs-redis:
    image: redis:6.2.4
    ports:
      - 127.0.0.1:6379:6379
