version: '2'
services:
  sabinolabs-app:
    image: sabinolabs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sabinolabs-postgresql:5432/sabinoLabs
  sabinolabs-postgresql:
    extends:
      file: postgresql.yml
      service: sabinolabs-postgresql
