apiVersion: v1
kind: Secret
metadata:
  name: sabinolabs-postgresql
  namespace: sabino-labs
  labels:
    app: sabinolabs-postgresql
type: Opaque
data:
  postgresql-password: Mzc3OGRjNjg1ODFhZTc4OWQ3NWU2MGFiNGQxZTJiNDEzMmZlNTY2ZTA1MGZlZWJhZjk0OGViZmQ0NzMw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabinolabs-postgresql
  namespace: sabino-labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabinolabs-postgresql
  template:
    metadata:
      labels:
        app: sabinolabs-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: sabinoLabs
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sabinolabs-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: sabinolabs-postgresql
  namespace: sabino-labs
spec:
  selector:
    app: sabinolabs-postgresql
  ports:
    - port: 5432
